### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by benthorner**

### CODE REVIEW

**Comment by benthorner** [comment]
@vincent-psarga we've now started using the gem 🎉 (https://github.com/alphagov/content-publisher/pull/2109).

The only problem was a typo - fixed here.

**Comment by vincent-psarga** [comment]
great :) I'm glad to know it wasn't completely useless for me to extract that as a gem :)

**Comment by harrylewis** [comment]
@vincent-psarga this tool has been great to use! Is it possible to get this PR merged? This typo caused a bit of a rocky start for me using the gem, and I'd love to see it merged so others don't experience the same.

**Comment by benthorner** [comment]
@vincent-psarga @blethier @cbliard any chance of getting this in?

I also spotted a missing/misleading `require` in the README, which I'd like to fix.

Might be worth adding one or two more contributors to the repo, if you're struggling for time. Appreciate this is probably a niche repo compared to your day-to-day jobs.

**Comment by vincent-psarga** [comment]
Sorry I completely forgot to merge it when I've read it.
Thanks for bumping the issue. It was kind of a pet project so we don't really spend time checking it ;)

**Comment by benthorner** [comment]
That's OK, glad it's in now.

We're using this in a few of our repos, so it's nice we can contribute to the original.

I've raised another one line PR for the other change I mentioned, if you could 👀: https://github.com/hiptest/i18n-coverage/pull/11.

**Pull request merged**
